### ISSUE TITLE
このリポジトリのライセンスを設定する

### ISSUE THREAD

**Issue by vvakame** [TechBooster/C89-FirstStepReVIEW-v2#2]
LICENSEファイル置くのとpackage.jsonのライセンス欄に書く

**Comment by vvakame** [comment]
コレ必要だわ感。

**Comment by kubosho** [comment]
自分が作ったRe:VIEW boilerplateでtechbooster-doujin.styを使っているのですが、これのライセンスがどうなるのか気になります。
https://github.com/kubosho/review-boilerplate/tree/master/articles/sty

**Comment by rb-de0** [comment]
同じく・・・。
techbooster-doujin.sty を使いたいのですがライセンスってどうなっているのか気になります。

**Comment by mhidaka** [comment]
@kubosho @rb-de0 基本的な指標として次のように考えています。

 * 文章、イラストデータについては著作物の権利を権利者に留保する
 * 設定ファイル、テンプレートなど制作環境に関してはMITライセンス（無保証かつ極ゆるいライセンス形態をとりたいため）。

techbooster-doujin.sty についてはすでに多くのサークルで利用実績もありますので
リポジトリなどで公開を予定しているのであればMITライセンスで運用ください。

# 現在、より使いやすくしていきたいとかんがえており、renameして本家リポジトリへのコントリビュートを相談中です。
# 一旦Readme.mdへの追記（MITライセンスとして宣言）しておきます。

余談ですが本リポジトリにおいてこのあたりのスタイルファイルは、
Re:VIEW最新版へ追従していきますのでウォッチしておいてもらえるとアフターフォローしやすくて助かります
（次の冬コミ向けの版でより使いやすくするための変更が入る見込み）。

**Comment by rb-de0** [comment]
@mhidaka ありがとうございます！
リポジトリで公開する予定ですので、MITライセンスとして公開させていただきます。

**Comment by kubosho** [comment]
@mhidaka 
ありがとうございます。MIT Licenseに沿って自分のリポジトリで使っているものに関しては次のようにライセンスを追記しています。
https://github.com/kubosho/review-boilerplate/blob/master/articles/sty/techbooster-doujin.sty#L1-L2

**Comment by vvakame** [comment]
#35 はmergeされ、本リポジトリに含まれる内容について自由に利用可能になった認識です。
