### ISSUE TITLE
ebookブランチでヘッダに第0章が表示されてしまう問題

### ISSUE THREAD

**Issue by mhidaka** [TechBooster/C89-FirstStepReVIEW-v2#29]
現在：
![2016-01-29 17 01 16](https://cloud.githubusercontent.com/assets/322019/12670356/2444e0c6-c6ab-11e5-86eb-4c65f9d39586.png)

これを出ないように直したい

**Comment by k16shikano** [comment]
つ https://github.com/TechBooster/C89-FirstStepReVIEW-v2/pull/30

**Comment by mhidaka** [comment]
merged!
