### ISSUE TITLE
setup.shのprh.ymlが404になっています

### ISSUE THREAD

**Issue by nyamadan** [TechBooster/C89-FirstStepReVIEW-v2#52]
こちらのurlが404になっているようです
https://github.com/TechBooster/C89-FirstStepReVIEW-v2/blob/master/setup.sh#L9

**Comment by mhidaka** [comment]
お。チェックします。
最新のdevelopをmasterに切り替え忘れてる気がします。

**Comment by vvakame** [comment]
setup.shメンテしてなかった(小声

**Comment by vvakame** [comment]
メンテした(developをmasterにmergeするのはいつやっていいのか謎なので適当にやってくれ感

**Comment by mhidaka** [comment]
いまからやりますー

**Comment by mhidaka** [comment]
@nyamadan お待たせしました。

**Comment by yamada-y** [comment]
👍
